### ISSUE TITLE
convert pine to python

### ISSUE THREAD

**Issue by it-viktor** [TomCallan/pyine#5]
Hello, I found your post "I will convert any tradingview indicator into a python indicator» 
but i can't contact you on the site - fiverr
Can I order a convert strategy to python?

**Comment by TomCallan** [comment]
Hi sorry, I thought that fiverr gig had been archived so I haven't been checking my account. That said, I'd happily give your project a look over if you want to send it to me (tomcallan0@outlook.com).

**Comment by it-viktor** [comment]
> Hi sorry, I thought that fiverr gig had been archived so I haven't been checking my account. That said, I'd happily give your project a look over if you want to send it to me ([tomcallan0@outlook.com](mailto:tomcallan0@outlook.com)).

I send email but don't get a response

**Comment by TomCallan** [comment]
Yeah don't worry I've been taking a look. Pretty much translated the first file and the second shouldn't take too much longer. I'll get back to you with a price once they're finished but honestly itd be easier if you tell me what you'd be willing to pay.
________________________________
