### ISSUE TITLE
a problem on test.py

### ISSUE THREAD

**Issue by darkjackx** [TomCallan/pyine#6]
engine = btv2.engine(data)
TypeError: engine.__init__() missing 1 required positional argument: 'data'

sorry, i am new to  python

**Comment by TomCallan** [comment]
@darkjackx The dev branch contains a lot of redundant code / code which doesn't work. Running dashboard.py should give you an example of the pyine system, however most of it is still not implemented. If you have anything specific you'd like to implement, email me at tomcallan0@outlook.com
