### ISSUE TITLE
`ModuleNotFoundError: No module named 'pyine.indicators'`

### ISSUE THREAD

**Issue by hemangjoshi37a** [TomCallan/pyine#7]
`import pyine` gives this error :
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [3], line 1
----> 1 import pyine

File ~/.local/lib/python3.11/site-packages/pyine/__init__.py:5
      2 __version__ = "1.1.2"
      4 from .convert import convert
----> 5 from .indicators import *

ModuleNotFoundError: No module named 'pyine.indicators'
```

**Comment by TomCallan** [comment]
@hemangjoshi37a unfortunately importing pyine as a package is not yet integrated into the current stack. Pyine is undergoing some large changes and as such the code here should be assumed to be unreliable. If you'd like to see the general overview of the stack, download the 'dev' branch and run dashboard.py. If you have anything specific you'd like to use pyine for, email me at tomcallan0@outlook.com and I should be able to help you.

**Comment by hemangjoshi37a** [comment]
@TomCallan  I ran the `dashboard.py` file but I dont know what to do with it. is there any documentation reagarding how to use this  ?
![Screenshot from 2023-02-20 23-56-46](https://user-images.githubusercontent.com/12392345/220177998-40e41987-5b10-4b56-bea1-1ae9c9f5cde8.png)

**Comment by hemangjoshi37a** [comment]
Also the `readme.md` file of this repo is very badly written if you give me the purpose and the use cases then we can rewrite the readme.

**Comment by TomCallan** [comment]
@hemangjoshi37a The dashboard is intended to allow you to write / optimise / backtest strategies although I have yet to write a set of docs. As far as the readme, do you have discord? I'd be happy to discuss your ideas on the pyine discord server. https://discord.gg/rtW4tagG
